default:
  image: gradle:9.2.1-jdk21-corretto
  tags:
    - global
services:
  - docker:29-dind
stages:
  - pre-build
  - build
  - test
  - build-image
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

verify-gradle-version-job:
  stage: pre-build
  script: |
    # Sanity check that gradle from docker image is the same version as is specified in gradle wrapper properties.
    # Gradle from docker image is used to avoid constant downloading of gradle wrapper.
    GRADLE_VERSION=$(gradle --version | grep "^Gradle " | awk '{print $2}')
    GRADLE_WRAPPER_VERSION=$(grep 'distributionUrl' gradle/wrapper/gradle-wrapper.properties \
      | sed -E 's/.*gradle-([0-9.]+)-bin\.zip/\1/')
    
    if [ "$GRADLE_VERSION" != "$GRADLE_WRAPPER_VERSION" ]; then
      echo "Gradle image version: $GRADLE_IMAGE_VERSION"
      echo "Gradle wrapper version: $WRAPPER_VERSION"
      echo "Please update either the Docker image or the wrapper version to match."
      exit 1
    fi

build-job:
  stage: build
  script:
    - gradle build --console=plain
  artifacts:
    when: always
    paths:
      - app/build/reports/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - app/build
